### ISSUE TITLE
username-in-sentinel

### ISSUE THREAD

**Issue by akshaysaxen** [Azure/Azure-Sentinel#1940]
in my project if any any alerts is triggered then no user name information is visible. do you have any idea why this issue occurred??
<img width="842" alt="Capture" src="https://user-images.githubusercontent.com/80679464/111143830-49906100-85ac-11eb-9138-e85977bb6c80.PNG">

**Comment by shainw** [comment]
@akshaysaxen - It depends on the Rules you have enabled.  Can you share a couple examples?  GitHub has a direct mapping for each of the rules to Entities that they produce.  You can see this in the YAML.  For example for this [rule](https://github.com/Azure/Azure-Sentinel/blob/master/Detections/SecurityEvent/RDP_Nesting.yaml), the entityMappings portion shows the Account -

```
entityMappings:
  - entityType: Account
    fieldMappings:
      - identifier: FullName
        columnName: AccountCustomEntity
  - entityType: Host
    fieldMappings:
      - identifier: FullName
        columnName: HostCustomEntity
  - entityType: IP
    fieldMappings:
      - identifier: Address
        columnName: IPCustomEntity
```
